export const t = {
  app: {
    nom: "Gestió de Residus",
    slogan: "Gestió operativa de recollides",
  },
  auth: {
    titol: "Accés a l'aplicació",
    usuari: "Usuari",
    contrasenya: "Contrasenya",
    entrar: "Entrar",
    sortir: "Sortir",
    errorCredencials: "Usuari o contrasenya incorrectes",
  },
  nav: {
    tauler: "Tauler",
    historial: "Historial",
    bustiaFotos: "Bústia de fotos",
    camions: "Camions",
    usuaris: "Usuaris",
    clients: "Clients",
    configuracio: "Configuració",
  },
  tauler: {
    titol: "Tauler de despatx",
    vistaKanban: "Kanban",
    vistaCalendari: "Calendari",
    assignar: "Assignar",
    verificarAssignacions: "Verificar assignacions",
    publicarJornada: "Publicar jornada",
    senseAssignar: "Sense assignar",
    assignantA: "Assignant a",
    viatgesSeleccionats: "viatges seleccionats",
    cancellarAssignacio: "Cancel·lar",
    ok: "OK",
    avui: "Avui",
    jornada: "Jornada",
    publicar: "Publicar",
    esborrany: "Esborrany",
    publicat: "Publicat",
  },
  viatge: {
    client: "Client",
    tipusResidu: "Tipus de residu",
    hora: "Hora",
    adreca: "Adreça",
    camio: "Camió",
    conductor: "Conductor",
    estat: "Estat",
    fotos: "Fotos",
    instruccions: "Instruccions",
    historialCanvis: "Historial de canvis",
    pesReal: "Pes real (kg)",
    observacions: "Observacions",
    noAssignat: "Sense assignar",
    tancar: "Tancar",
    guardar: "Guardar",
    reasignar: "Reasignar",
    moureDia: "Moure a un altre dia",
    cancellar: "Cancel·lar viatge",
    deixarPendent: "Deixar pendent",
  },
  estats: {
    pendent: "Pendent",
    en_cami: "En camí",
    arribat: "Arribada a client",
    recollit_ok: "Recollit sense incidència",
    recollit_incidencia: "Recollit amb incidència",
    a_planta: "A la planta",
    descarrega_completada: "Descàrrega completada",
  } as Record<string, string>,
  incidencies: {
    titol: "Registrar incidència",
    tipus: "Tipus d'incidència",
    retard: "Retard",
    client_tancat: "Client tancat / ningú",
    residu_no_apte: "Residu no apte o diferent",
    problema_camio: "Problema amb el camió",
    altra: "Altra",
    detall: "Detall",
    estimacioTemps: "Estimació de temps (minuts)",
    afegirFoto: "Afegir foto",
    enviar: "Enviar incidència",
    gpsAutomatic: "GPS i hora registrats automàticament",
    fotoObligatoria: "Cal afegir una foto per a aquest tipus d'incidència",
  } as Record<string, string>,
  conductor: {
    titol: "Els meus viatges d'avui",
    senViatges: "No tens viatges assignats per avui",
    telefon: "Trucar al client",
    navegar: "Navegar",
    enCami: "En camí",
    arribada: "Arribada a client",
    recollitOk: "Recollit sense incidència",
    recollitIncidencia: "Recollit amb incidència",
    aPlanta: "A la planta",
    descarregaCompletada: "Descàrrega completada",
  },
  bustia: {
    titol: "Bústia de fotos pendents",
    assignarViatge: "Assignar al viatge",
    descartar: "Descartar",
    fotoPendent: "Foto sense assignar",
    origen: "Origen",
  },
  historial: {
    titol: "Historial de viatges",
    filtrarData: "Filtrar per data",
    filtrarCamio: "Filtrar per camió",
    filtrarClient: "Filtrar per client",
    exportarCSV: "Exportar CSV",
    noResultats: "No hi ha resultats per als filtres seleccionats",
  },
  camions: {
    titol: "Gestió de camions i conductors",
    nou: "Nou camió",
    nom: "Nom",
    matricula: "Matrícula",
    color: "Color",
    conductor: "Conductor assignat",
    senseCondutor: "Sense conductor",
    guardar: "Guardar",
  },
  usuaris: {
    titol: "Gestió d'usuaris",
    nou: "Nou usuari",
    nom: "Nom complet",
    usuari: "Nom d'usuari",
    contrasenya: "Contrasenya",
    rol: "Rol",
    telefon: "Telèfon",
    telegramChatId: "Telegram Chat ID",
    actiu: "Actiu",
    gestio: "Gestió",
    conductor: "Conductor",
    guardar: "Guardar",
    eliminar: "Desactivar",
  },
  errors: {
    generic: "S'ha produït un error. Torna-ho a intentar.",
    noAutoritzat: "No tens permís per fer aquesta acció.",
    noTrobat: "No s'ha trobat el recurs.",
  },
};
